=== api-evangelist/7shifts/json-schema/7shifts-shift-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/7shifts/refs/heads/main/json-schema/7shifts-shift-schema.json",
  "title": "Shift",
  "type": "object",
  "description": "7shifts Shift resource.",
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64"
    },
    "user_id": {
      "type": "integer",
      "format": "int64",
      "nullable": true
    },
    "location_id": {
      "type": "integer",
      "format": "int64"
    },
    "department_id": {
      "type": "integer",
      "format": "int64"
    },
    "role_id": {
      "type": "integer",
      "format": "int64"
    },
    "start": {
      "type": "string",
      "format": "date-time",
      "description": "Start datetime of the shift. UTC in ISO8601 format."
    },
    "end": {
      "type": "string",
      "format": "date-time",
      "description": "End datetime of the shift. UTC in ISO8601 format."
    },
    "hourly_wage": {
      "type": "integer",
      "description": "The hourly wage for this shift, in cents."
    },
    "draft": {
      "type": "boolean",
      "description": "Publication status indicator."
    },
    "open": {
      "type": "boolean",
      "description": "Indicates an unassigned shift available for requests."
    },
    "station": {
      "type": "string",
      "nullable": true
    },
    "attendance_status": {
      "type": "string",
      "enum": [
        "none",
        "sick",
        "no_show",
        "late"
      ]
    },
    "breaks": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "created": {
      "type": "string",
      "format": "date-time"
    },
    "modified": {
      "type": "string",
      "format": "date-time"
    }
  }
}

=== api-evangelist/7shifts/examples/7shifts-shift-example.json
{
  "id": 12345,
  "user_id": 12345,
  "location_id": 12345,
  "department_id": 12345,
  "role_id": 12345,
  "start": "2026-06-02T14:30:00Z",
  "end": "2026-06-02T14:30:00Z",
  "hourly_wage": 12345,
  "draft": true,
  "open": true,
  "station": "example",
  "attendance_status": "none",
  "breaks": [],
  "created": "2026-06-02T14:30:00Z",
  "modified": "2026-06-02T14:30:00Z"
}
